name: Send message to slack

description: 'Send resuls on slack'
author: 'Hugging Face'
inputs:
  slack_channel:
    required: true
    type: string
  title:
    required: true
    type: string
  status:
    required: true
    type: string
  slack_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Post results Slack channel
      id: post-slack
      uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ inputs.slack_channel }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "Slow integration tests on ${{ toJson(inputs.title) }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🤗 Results of the ${{ toJSON(inputs.title) }} tests."
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Result: ${{ inputs.status }} Commit: ${{ github.event.pull_request.html_url || github.event.head_commit.url }} Action URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_token }}

# {
#     "text": "Slow integration tests on "FA2 tests - models/llama"",
#     "blocks": [
#       {
#         "type": "header",
#         "text": {
#             "type": "plain_text",
#             "text": "🤗 Results of the "FA2 tests - models/llama" tests."
#         }
#       },
#       {
#         "type": "section",
#         "text": {
#           "type": "mrkdwn",
#           "text": "Result: success Commit: https://github.com/huggingface/transformers/commit/510ac070f7a74d93e0cd34233e59d7d60dbd39a0 Action URL: https://github.com/huggingface/transformers/actions/runs/8136052993"
#         }
#       }
#     ]
#   }