name: Build pr ci-docker

on:
  push:
    branches:
      - change-ci
  repository_dispatch:
  workflow_call:
    inputs:
      image_postfix:
        required: true
        type: string
  schedule:
    - cron: "17 0 * * *"


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        file: ["quality", "consistency", "custom-tokenizers", "torch-light", "tf-light", "exotic-models", "torch-tf-light"]  # Add your file names here

    if: |
      contains(github.event.head_commit.message, '[push-ci-image]')  && 
      contains(github.actor, 'transformers') && 
      ${{ !cancelled() && (success() || failure()) }}

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build ${{ matrix.file }}.dockerfile
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          build-args: |
            REF=main
          file: "./docker/${{ matrix.file }}.dockerfile"
          push: true
          tags: huggingface/transformers-${{ matrix.file }}