name: Slow tests on important models (on Push - A10)

on:
  push:
    branches: [ add-new-push-test-workflow ]

env:
  RUN_SLOW: "yes"
  IS_GITHUB_CI: "1"
  OUTPUT_SLACK_CHANNEL_ID: "C06L2SGMEEA"
  HF_HUB_READ_TOKEN: ${{ secrets.HF_HUB_READ_TOKEN }}

jobs:
  get_modified_models:
    name: "Get all modified files"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@3f54ebb830831fc121d3263c1857cfbdc310cdb9 #v42
        with:
          files: src/transformers/models/**
      - name: Run step if only the files listed above change
        if: steps.changed-files.outputs.any_changed == 'true'
        id: set-matrix
        run: |
            model_arrays=()
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                model_path="${file#*models/}"
                model_path="models/${model_path%%/*}"
                if grep -qFx "$model_path" utils/important_models.txt; then
                    echo "$model_path was changed"
                    # Append the file to the matrix string
                    model_arrays+=("$model_path")
                fi
            done
            matrix_string=$(printf '"%s", ' "${model_arrays[@]}" | sed 's/, $//')
            echo "matrix=[$matrix_string]" >> $GITHUB_OUTPUT
  test_modified_files:
    needs: get_modified_models
    name: Run slow tests on modified models
    runs-on: [single-gpu, nvidia-gpu, a10, ci] # TODO: uncomment this
    container:
      image: huggingface/transformers-all-latest-gpu
      options: --gpus all --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    if: ${{ needs.get_modified_models.outputs.matrix != '[]' && needs.get_modified_models.outputs.matrix != '' }}
    strategy:
      fail-fast: false
      matrix: 
        model-name: ${{ fromJson(needs.get_modified_models.outputs.matrix) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install locally transformers & other libs
        run: |
          pip install -e ".[testing]" 
          MAX_JOBS=4 pip install flash-attn --no-build-isolation
          pip install bitsandbytes
      - name: NVIDIA-SMI
        run: |
          nvidia-smi
      - name: Run FA2 tests
        id: run_fa2_tests
        run:
          pytest -m "flash_attn_test" tests/${{ matrix.model-name }}/test_modeling_*
      - name: Post results Slack channel
        if: always()
        id: post-slack-fa2
        uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ env.OUTPUT_SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Slow FA 2 tests on ${{ matrix.model-name }} result: ${{ steps.run_fa2_tests.conclusion }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "FA2 tests for ${{ matrix.model-name }}: ${{ steps.run_fa2_tests.conclusion }}\n\n Commit: ${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n\n Action URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_CIFEEDBACK_BOT_TOKEN }}

      - name: Run integration tests
        id: run_integration_tests
        if: always()
        run:
          pytest -k "IntegrationTest" tests/${{ matrix.model-name }}/test_modeling_*
      - name: Post results Slack channel
        if: always()
        id: post-slack-integration-tests
        #uses: slackapi/slack-github-action@v1.25.0
        uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ env.OUTPUT_SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Slow integration tests on ${{ matrix.model-name }} result: ${{ steps.run_integration_tests.conclusion }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Integration tests on ${{ matrix.model-name }}: ${{ steps.run_integration_tests.conclusion}}\n\n Commit: ${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n\n Action URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_CIFEEDBACK_BOT_TOKEN }}